### PR TITLE
Update MD files

### LINKED ISSUE #90: Update MD files
### Description

File `README.md` is pretty up-to-date right now, but other files ( `CONTRIBUTING.md`, `MAINTAINERS.md` and maybe more) may require some update. They were pretty much just copied from Keycloak and are not aligned with keycloak-client repository.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by mposolda**
closes #90

### CODE REVIEW

**Review by rmartinc — DISMISSED** [review]
@mposolda LGTM! Just a little suggestion in a phrase which was confusing to me.

**Review by pskopek — DISMISSED** [review]
LGTM including Ricky's suggestion.

**Comment by mposolda** [comment]
@rmartinc @pskopek Added the suggestion, Thanks!

**Review by jonkoops — APPROVED** [review]

**Review by graziang — APPROVED** [review]

**Comment by mposolda** [comment]
Thanks everyone for the review!

**Pull request merged**
