### PR TITLE
Testing of Keycloak admin client with Keycloak 24, 25 and nightly. GH…

### PR DESCRIPTION
**Pull request by mposolda**
… actions setup updates to allow caching
closes keycloak/keycloak#31868

- Ability to test admin-client and admin-client-jee with latest Keycloak 24, Keycloak 25 and Keycloak nightly

- Adding all of those to GH actions

- Improvements in GH actions to allow caching etc, so it is possible to build project first and then the subsequent matrix builds using stuff from maven cache (Similar setup like keycloak main repository)

### CODE REVIEW

**Review by rmartinc — APPROVED** [review]
LGTM @mposolda!

**Review by graziang — APPROVED** [review]
Thanks @mposolda, LGTM!

**Review by pskopek — APPROVED** [review]
LGTM!

**Comment by mposolda** [comment]
@rmartinc @pskopek @graziang Thanks!

**Pull request merged**
